- name: "Installing VIM"
  yum:
    name: vim
    state: present
- name: "Installing iperf3"
  yum:
    name: iperf3
    state: present
- name: "Installing bind-utils"
  yum:
    name: bind-utils
    state: present
- name: "Installing python3"
  yum:
    name: python3
    state: latest
- name: "Installing python3-devel"
  yum:
    name: python3-devel
    state: latest
- name: "Installing docker"
  pip:
    name: docker
    state: latest
    executable: pip3
- name: "Installing psutil"
  pip:
    name: psutil
    state: latest
    executable: pip3
- name: "Installing pycryptodome"
  pip:
    name: pycryptodome
    state: latest
    executable: pip3
- name: Make users passwordless for sudo in group wheel
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
- name: "Create user jsimon and generate SSH keys"
  user:
    name: jsimon
    password: $6$.LM.OTlR8/qB4NK0$VuB2nXERFxWCc170ELjitPJrGXFZhqaoOvS37wEoolpfOWxOulVoYaDL96ebi1mwcoOHVt3o0VyPLNO9Cf8nH0
    append: yes
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_file: .ssh/id_rsa_jsimon
    ssh_key_bits: 4096
    force: no
- name: "Create user tkolesn and generate SSH keys"
  user:
    name: tkolesn
    password: $6$.LM.OTlR8/qB4NK0$VuB2nXERFxWCc170ELjitPJrGXFZhqaoOvS37wEoolpfOWxOulVoYaDL96ebi1mwcoOHVt3o0VyPLNO9Cf8nH0
    append: yes
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_file: .ssh/id_rsa_tkolesn
    ssh_key_bits: 4096
    force: no
- name: "Disable root login over SSH"
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify:
    - Restart SSHD
- name: "Creates directory /var/log/dathena/dtq"
  file:
    path: /var/log/dathena/dtq
    state: directory
    recurse: yes
- name: "Creates directory /var/log/dathena/dpm"
  file:
    path: /var/log/dathena/dpm
    state: directory
    recurse: yes
- name: "Creates directory /var/log/dathena/reporting"
  file:
    path: /var/log/dathena/reporting
    state: directory
    recurse: yes
- name: "Creates file /var/log/dathena/dtq/.keep"
  file:
    path: /var/log/dathena/dtq/.keep
    state: touch
- name: "Creates file /var/log/dathena/dpm/.keep"
  file:
    path: /var/log/dathena/dpm/.keep
    state: touch
- name: "Creates file /var/log/dathena/reporting/.keep"
  file:
    path: /var/log/dathena/reporting/.keep
    state: touch